/* This file is automatically generated. DO NOT EDIT. */

#include <stdint.h>
#include "platform_support.h"

const power_domain_support_info_t PLATFORM_SUPPORT_TABLE[] = {
	[0x2A]	{0x2A,	"SANDYBRIDGE",	false,	true,	true,	true},
	[0x2D]	{0x2D,	"SANDYBRIDGE_EP",	true,	true,	false,	true},
	[0x3A]	{0x3A,	"IVYBRIDGE",	false,	true,	true,	true},
	[0x3C]	{0x3C,	"HASWELL1",	true,	true,	false,	true},
	[0x3F]	{0x3F,	"HASWELL_EP",	true,	true,	false,	true},
	[0x45]	{0x45,	"HASWELL2",	true,	true,	false,	true},
	[0x46]	{0x46,	"HASWELL3",	true,	true,	false,	true},
	[0x4E]	{0x4E,	"SKYLAKE1",	true,	true,	false,	true},
	[0x4F]	{0x4F,	"BROADWELL2",	true,	true,	false,	true},
	[0x5C]	{0x5C,	"APOLLOLAKE",	true,	true,	false,	true},
	[0x5E]	{0x5E,	"SKYLAKE2",	true,	true,	false,	true},
	[0x8e]	{0x8e,	"KABYLAKE",	true,	true,	true,	true},
	[0x9e]	{0x9e,	"COFFEELAKE2",	true,	true,	false,	true},
	[0xD4]	{0xD4,	"BROADWELL",	true,	true,	true,	true},
};

const power_domain_support_info_t
	PLATFORM_NOT_SUPPORTED = {0x00, 0, false, false, false, false};

const uint32_t KNOWN_PLATFORM_ID_SET[] = {
	0x2A,
	0x2D,
	0x3A,
	0x3C,
	0x3F,
	0x45,
	0x46,
	0x4E,
	0x4F,
	0x5C,
	0x5E,
	0x8e,
	0x9e,
	0xD4,
};

const int NUM_PLATFORMS_SUPPORTED = 14;

